name: Deploy the giroux backend for dev environment

on:
  push:
    branches:
      - dev

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ap-south-1

  serverless_deploy:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node_modules
        run: npm i

      - name: Deploy using serverless
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}